config/routes.rb
Pomar::Application.routes.draw do
  resources :tasks

  get "main/index"

  resources :users
  resources :sessions
  resources :projects

  match '/signup', :to => 'users#new', :as => 'signup'
  match '/confirm', :to => 'users#confirm', :as => 'confirm'
  match '/signin', :to => 'sessions#new', :as => 'signin'
  match '/signout', :to => 'sessions#destroy'
  match '/main', :to => 'main#index', :as => 'main'
  match '/users/:id/password', :to => 'users#password', :as => 'password'
  match '/main/project/:id', :to => 'main#project'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :confirmation_key, :dependent => :destroy

	before_create :make_hashed_password
	before_update :make_hashed_password
	after_create :create_confirmation_key

	attr_accessor :password, :password_confirmation # needed because they don't exist in database
	attr_protected :hashed_password, :sha1_salt, :confirmed

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name,		:presence => true, :length => { :maximum => 60 }
	validates :email,		:presence => true, :length => { :maximum => 60 }, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
	validates :username,	:presence => true, :length => { :maximum => 60 }, :uniqueness => { :case_sensitive => false }
	validates :password,	:presence => true, :confirmation => true, :length => { :within => 6..20 }, :if => :password_validation_required?

	def password_validation_required?
		self.hashed_password.blank? or not @password.blank?
	end

	def make_hashed_password
		unless @password.blank?
			make_salt if self.sha1_salt.blank?
			self.hashed_password = User.encrypt(@password, self.sha1_salt)
		end
	end

	def create_confirmation_key
		#key = ConfirmationKey.create!(:key => User.encrypt(self.email, self.sha1_salt))
		#key.user = self
		#key.save
		key = ConfirmationKey.create!(:user => self, :key => User.encrypt(self.email, self.sha1_salt))
	end

	def make_salt
		self.sha1_salt = Digest::SHA1.hexdigest(self.username + Time.now.to_s)
	end

	def authenticated?(password)
		self.hashed_password == User.encrypt(password, self.sha1_salt)
	end

	def self.encrypt(password, salt)
		Digest::SHA1.hexdigest(password + salt)
	end

	def self.authenticate(username, password)
		user = find_by_username(username)
		return user if user && user.authenticated?(password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@title = "Pomar: Sign Up!"
		@user = User.new
	end

	def create
		# http://guides.rubyonrails.org/security.html
		# 6 Mass Assignment - Without any precautions Model.new(params[:model]) allows attackers to set any database column’s value.
		# @user = User.new(params[:user])

		@user = User.new
		@user.name = params[:user][:name]
		@user.email = params[:user][:email]
		@user.username = params[:user][:username]
		@user.password = params[:user][:password]
		@user.password_confirmation = params[:user][:password_confirmation]

		respond_to do |format|
			if @user.save
				key = ConfirmationKey.find_by_user_id(@user.id)
				Mailer.notify_signup(params[:user][:email], key.key).deliver

				format.html { redirect_to(@user, :notice => 'User was successfully created!') }
				format.xml  { render :xml => @user, :status => :created, :location => @user }
			else
				@title = "Pomar: Sign Up!"
				flash.now[:alert] = @user.errors.full_messages[0]
				format.html { render :action => "new" }
				#format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
			end
		end
	end

	def show
		@user = User.find(params[:id])

		respond_to do |format|
			format.html
			format.xml { render :xml => @user }
		end
	end

	def confirm
		if params[:key].blank? then
			flash.now[:alert] = 'Confirmation key required!'
		else
			unless ConfirmationKey.exists?(:key => params[:key]) then
				flash.now[:alert] = 'Error: The confirmation key is invalid!'
			else
				key = ConfirmationKey.find_by_key(params[:key])
				user = key.user
				user.confirmed = true

				if user.save(:validate => false) # active record should not validate fields, because password and password_confirmation don't exist now
					key.destroy
					flash.now[:notice] = 'Your account was confirmed!'
				else
					flash.now[:alert] = 'Error: It was not possible to confirm the user!'
				end
			end
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def password
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		RAILS_DEFAULT_LOGGER.error('setting: ' + params[:setting] + "\n")
		RAILS_DEFAULT_LOGGER.error('params[:user]: ' + params[:user].collect { |k,v| "[#{k},#{v}]"}.join + "\n")

		respond_to do |format|
			if @user.update_attributes(params[:user])
				flash.now[:notice] = 'Your account was updated!'
				format.html { render :action => params[:setting] }
			else
				RAILS_DEFAULT_LOGGER.error('update_attributes error!!!')
				format.html { render :action => params[:setting] }
			end
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
Account | <%= link_to "Password", "/users/" + current_user.id.to_s + "/password" %>

<!--<p id="notice"><%= notice %></p>-->

<%= form_for(current_user) do |f| %>
	<%= hidden_field_tag :setting, 'edit' %>

	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :username %><br />
		<%= f.text_field :username %>
	</div>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>

	<br />
	<div class="actions">
		<%= f.submit 'Save' %>
	</div>
<% end %>

<br />
<%= link_to 'Cancel', main_path %>

app/views/users/password.html.erb
<%= link_to "Account", edit_user_path(current_user) %> | Password

<p id="notice"><%= notice %></p>

<%= form_for(current_user) do |f| %>
	<%= hidden_field_tag :setting, 'password' %>

	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :password, 'New password' %><br />
		<%= f.text_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation, 'Confirmation' %><br />
		<%= f.text_field :password_confirmation %>
	</div>

	<br />
	<div class="actions">
		<%= f.submit 'Change' %>
	</div>
<% end %>

<br />
<%= link_to 'Cancel', main_path %>